version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-twilog-web-archiver-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - v1-twilog-web-archiver-deps-
      - run: poetry install
      - save_cache:
          key: v1-twilog-web-archiver-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "/home/circleci/.cache/pypoetry/virtualenvs"
      - run:
          command: |
            mkdir test-reports
            poetry run pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
