version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: python-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            poetry install
      - save_cache:
          key: python-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "/home/circleci/.cache/pypoetry/virtualenvs"
      - run:
          command: |
            poetry run pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
